---
io-services:
  reader:
    class: org.jlab.ersap.actor.coda.engine.CodaEtSourceEngine
    name: Source
  writer:
    class: org.jlab.ersap.actor.coda.engine.CodaFileSinkEngine
    name: Sink
services:
  - class: org.jlab.ersap.actor.coda.engine.EventIdentificationEngine
    name: EventId
configuration:
  io-services:
    reader:
      et_name: "/tmp/et_experiment_2_ER2"
      et_port: 23911
      et_station: "ersap"
      fifo_capacity: 128
    writer:
      hist_bins: 100
      hist_min: 100
      hist_max: 8000
      delta_t: 20
      #> grid_size defines a layout for histogram visualization
      #> (e.g. 5 will plot 25 histograms in 5x5 matrix)
      grid_size: 2
  services:
    EventId:
      sliding_window: 40
      multiplicity: 2
mime-types:
  - binary/data-evio
  - binary/data-jobj
