---
io-services:
  reader:
    class: org.jlab.ersap.actor.coda.engine.CodaEtSourceEngine
    name: Source
  writer:
    class: org.jlab.ersap.actor.coda.engine.CodaFileSinkEngine
    name: Sink
services:
  - class: org.jlab.ersap.actor.coda.engine.EventIdentificationEngine
    name: EventId
configuration:
  io-services:
    reader:
      et_name: "/tmp/et_experiment_2_ER2"
      et_port: 23911
      et_station: "ersap"
      fifo_capacity: 128
  services:
    EventId:
      sliding_window: 40
      multiplicity: 2
mime-types:
  - binary/data-evio
  - binary/data-jobj
