---
io-services:
  reader:
    class: org.jlab.ersap.actor.coda.engine.CodaEtSourceEngine
    name: Source
  writer:
    class: org.jlab.ersap.actor.coda.engine.CodaFileSinkEngine
    name: Sink
services:
  - class: org.jlab.ersap.actor.coda.engine.EventIdentificationEngine
    name: EventId
configuration:
  io-services:
    reader:
      et_name: "ascvsd"
      et_station: "ersap"
  services:
    EventId:
      sliding_window: 40
      multiplicity: 2
mime-types:
  - binary/data-evio
  - binary/data-jobj
